mappings:
  RecommendedProductsModifier_Form: Sunnysideup\EcommerceAlsoRecommended\Forms\RecommendedProductsModifier_Form
  RecommendedProductsModifier: Sunnysideup\EcommerceAlsoRecommended\Modifiers\RecommendedProductsModifier
  EcommerceAlsoRecommendedDOD: Sunnysideup\EcommerceAlsoRecommended\Model\EcommerceAlsoRecommendedDOD
