mappings:
  RecommendedProductsModifier_Form: Sunnysideup\EcommerceAlsoRecommended\Forms\RecommendedProductsModifierForm
  RecommendedProductsModifier: Sunnysideup\EcommerceAlsoRecommended\Modifiers\RecommendedProductsModifier
  EcommerceAlsoRecommendedDOD: Sunnysideup\EcommerceAlsoRecommended\Model\EcommerceAlsoRecommendedDOD
